### ISSUE TITLE
Prettier complains about use of await

### ISSUE THREAD

**Issue by comfortablynick** [cyanzhong/vscode-jsbox#12]
The following test script to retrieve phone numbers from `$contact` executes fine in JSBox:
```js
/** @format */

const contacts = await $contact.fetch({key: 'FSG'});
let numbers = [];
for (let c of contacts) {
    console.log(`${c.givenName} ${c.familyName}`);
    for (let p of c.phoneNumbers) {
        if (p["label"] == "_$!<Mobile>!$_") {
            numbers.push(p["content"]);
        }
    }
}
console.log(numbers);
```
But in vscode, Prettier throws this error every time I save the file:
```js
await is a reserved word (3:17)
  1 | /** @format */
  2 | 
> 3 | const contacts = await $contact.fetch({key: 'FSG'});
    |                  ^
  4 | let numbers = [];
  5 | for (let c of contacts) {
  6 |     console.log(`${c.givenName} ${c.familyName}`);
```
I'm new to the async stuff so I may have something wrong here, but it seems in line with the documentation. I've tried many variations, including wrapping the call to `$contact` in an anonymous async function, but I always get some kind of error. Am I missing something?

Thanks!
Nick

**Comment by cyanzhong** [comment]
The reason is that you need to use await inside an async function, could you try the following pattern?

```js
async function() {
  const contacts = await $contact.fetch({key: 'FSG'});
}
```

JSBox wraps user scripts as async functions so that you can use await without async.
