### ISSUE TITLE
Set Host 命令无法使用

### ISSUE THREAD

**Issue by winwinyang** [cyanzhong/vscode-jsbox#2]
package.json 文件中 Set Host 命令设置错误，导致命令无法调用。
command 的描述应该为 setHost，而不是 extension.setHost

**Comment by cyanzhong** [comment]
Hmmm... 我改改

**Comment by cyanzhong** [comment]
你是说以哪种方式打开的时候无法使用？

你当前有打开 js 文件吗？

**Comment by winwinyang** [comment]
用 vscode 安装好插件以后，点击菜单中的 Set Host 选项来设置 Host 无反应，输入命令，会提示“command 'extension.setHost' not found命令”

**Comment by winwinyang** [comment]
今天又卸载安装插件测试了几次，偶尔会出现这种情况，不太清楚复现的原因
